@startuml

hide circle

skinparam Shadowing false
skinparam DefaultFontName "Ricty Diminished"
skinparam DefaultFontSize 14
skinparam DefaultFontStyle bold
skinparam classFontSize 16
skinparam classFontStyle bold
skinparam ArrowColor white
skinparam ArrowThickness 2
skinparam Padding 2
skinparam ClassBorderThickness 0

skinparam DefaultFontColor #444
skinparam BackgroundColor #99b32d
skinparam ClassBorderColor #99b32d
skinparam ClassHeaderBackgroundColor #c46
skinparam ClassBackgroundColor #fff
skinparam StereotypeCBackgroundColor #fff
skinparam classFontColor #fff

entity Admin {
  id
  --
  name
  email
  password
}

entity Work {
  id
  --
  title
  status
  uri
  released_date
  eye_catch
  description
  content
  like
  --
  admin_id
  parent_work_id
}

entity Tag {
  id
  --
  name
  category
}

entity WorkTag {
  id
  --
  work_id
  tag_id
}

entity Comment {
  id
  --
  name
  email
  content
  ip_address
  --
  work_id
  parent_comment_id
}

entity WorkLink {
  id
  --
  title
  url
  xorder
  --
  work_id
}

entity Album {
  id
  --
  title
  description
  price
  event
  xorder
  --
  work_id
}

entity Music {
  id
  --
  title
  description
  lyrics
  soundcloud_url
  xorder
  --
  album_id
}

entity Movie {
  id
  --
  title
  description
  youtube_url
  niconico_url
  xorder
  --
  work_id
}

entity Artwork {
  id
  --
  title
  description
  image
  xorder
  --
  work_id
}

entity Comic {
  id
  --
  title
  description
  xorder
  --
  work_id
}

entity ComicPage {
  id
  --
  image
  description
  nombre
  --
  work_id
}

entity WorkAuthor {
  id
  --
  role
  --
  work_id
  author_id
}

entity Author {
  id
  --
  name
  profile
  icon
  link
}

entity AuthorLink {
  id
  --
  site
  url
  name
  --
  author_id
}

Admin --{ Work
Work --{ WorkTag
WorkTag }-- Tag
Work ---{ Comment
Work --{ WorkLink
Work --{ Album
Album --{ Music
Work --{ Artwork
Work --{ Movie
Work --{ Comic
Comic --{ ComicPage
Author -{ WorkAuthor
WorkAuthor }- Work
Author --{ AuthorLink
Work |o- Work

@enduml
