version: '3'
services:
  db:
    image: mysql:8.0.23
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    cap_add:
      - SYS_NICE
    ports:
      - 3308:3306
    volumes:
      - ./.localdocker/mysql/lib/mysql:/var/lib/mysql
      - ./.localdocker/mysql/conf:/etc/mysql/conf.d
      - ./.localdocker/mysql/log:/var/log/mysql
