default: &default
  adapter:   mysql2
  encoding:  utf8
  collation: utf8_unicode_ci
  pool:      <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database:  <%= ENV['DATABASE_NAME'] %>
  host:      <%= ENV['DATABASE_HOST'] %>
  port:      <%= ENV['DATABASE_PORT'] %>
  username:  <%= ENV['DATABASE_USERNAME'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>
